language: python
python:
- '2.7'
env:
  - TOXENV=markdown-lint
install:
- apt-get install -y texlive-full
- pip install -q -r requirements.txt
- gem install mdl
- pip install tox
script: 
#- tox
- make html
matrix:
  fast_finish: true
#  allow_failures:
#   - env: TOXENV=markdown-lint
after_success: curl -X POST https://readthedocs.org/build/dueling-dogs-online-documentation
notifications:
  email: false 
  slack:
     secure: "mWOtroAwlMkFbSSHI4Vy5FLhIEIOKRVTT8AIvEEiBungdkOumYDIFCsWqB3nb6Ws3p6UudA3JWj5UzaV7x3P7qwOwm1WnrMUQXcdLUjnrDuwU7MwSqfRxq+yK9fHpMsF9aaDJcVfREaL6RUzN+sxrzD+S2rdZSimq8U/jnMYpTrPmi5JKyuKL3Zx0KDx/dTGLzE3QuO7TlfuQi+5cpZ3f5ETeIN22oi207MpmrwxGppeYfebqgxMpf4m4m5T28XYTFPMfoXhJnHp5sq0KdxaMFakrgxPhXaDQAtPcFgn+ITCSS44zjbOcLKLhMxSESecqWv8x63zIl+/pmQmYUEIdBCPGqpeiXqN2WVmzTwxwNXF/6x5otg7FZmsx+nr1G7Ll8uexV2DwwfPvBFhoD4bPyW+YHvXK7igmgMPZttcT1ST9uSolvYBOYtENVWLxKvM3jXn9nhvXQ49GWAB/MxkyjQGTu0dpiXgamplBpX8yoVR746dYC3DijH/vgL0ry7c0DH8CpH+m10KtvWGD1sLRKzZqOlFwXm+uIPbts7NheqbLIphuXIVUXfuN58qHdypyiO96WkdalsIuYJo4KoNC4pa5HJ0SnNm5rwzC/PcBnRjRmS1BV+hZ9skd25cfF4oyfudXadaQlIT1/q6LzcdRKFNLfnB5IEYrFdI0thFb9I="
